Support multihost

diff --git a/misc/setup_ios_host b/misc/setup_ios_host
--- a/misc/setup_ios_host
+++ b/misc/setup_ios_host
@@ -33,21 +33,14 @@ ping -q -o "$HOST" || { usage; echo Unable to ping host "'$HOST'" ; exit 1 ; }
 
 USERHOST="${USER}@${HOST}"
 
-UIDS=$(ssh ${USERHOST} "dscl . -list /Users UniqueID")
-[ -n "$UIDS" ] || { usage; echo "Unable to retrieve UIDs from $USERHOST ($UIDS)"; exit 1 ; }
-
 PASSWORD=$( ruby -e "config = eval File.read('$CONFIG'); puts config[:PASSWORD]" )
-USERS=$( ruby -e "config = eval File.read('$CONFIG'); puts config[:USERS].map{|e|e.split('@')[0]}" )
+USERS=$( ruby -e "config = eval File.read('$CONFIG'); puts config[:USERS]" )
 
 # Copy application, config file, and authorise application to use UI Automation.
-scp -r ${0%/*}/autostart_test_users.app ${USERHOST}:/Applications/
-scp $CONFIG ${USERHOST}:.parallel_calabash.iphonesimulator
+rsync -r --delete ${0%/*}/autostart_test_users.app ${USERHOST}:/Applications/
+rsync $CONFIG ${USERHOST}:.parallel_calabash.iphonesimulator
 ssh ${USERHOST} "ln -s .parallel_calabash.iphonesimulator .parallel_calabash.autostart"
 echo "${PASSWORD}" | ssh ${USERHOST} "sudo sqlite3 '/Library/Application Support/com.apple.TCC/TCC.db' 'INSERT or REPLACE INTO access VALUES(\"kTCCServiceAccessibility\",\"com.apple.ScriptEditor.id.autostart-test-users\",0,1,0,NULL)'"
-
-# Copy sshd plist and tweakrun script.
-rsync ${0%/*}/autostart_test_users.sshd.* ${USERHOST}:Autostart/
-rsync ${0%/*}/autostart_test_users.reboot.* ${USERHOST}:Autostart/
 
 # Supposedly skip checking vs localhost with vnc addresses. Not sure if this is needed.
 echo "${PASSWORD}" | ssh ${USERHOST} "sudo defaults write com.apple.ScreenSharing skipLocalAddressCheck -boolean YES"
@@ -56,19 +49,37 @@ echo "${PASSWORD}" | ssh ${USERHOST} "sudo defaults write com.apple.ScreenSharin
 ssh ${USERHOST} "echo n | ssh-keygen -q -f .ssh/id_rsa -N ''"
 ssh ${USERHOST} "(echo 'Host *' ; echo '    StrictHostKeyChecking no'; echo 'UserKnownHostsFile /dev/null') >> .ssh/config"
 
+# Reboot the auto-login user if the default keychain is not 'login' - otherwise Screen Sharing will not work. Only needed for master machine.
 ssh ${USERHOST} "sed -E 's/MAIN_USER/$USER/' </Users/$USER/Autostart/autostart_test_users.reboot.plist >/Users/$USER/Library/LaunchAgents/autostart_test_users.reboot.plist"
+rsync ${0%/*}/autostart_test_users.reboot.* ${USERHOST}:Autostart/
 
 uid=500
 
 echo About to mkusers
 
-os_version=$(ssh ${USERHOST} "sw_vers -productVersion")
-buddy_version=$(ssh ${USERHOST} "sw_vers -buildVersion")
-
 for nuser in $USERS ; do
 echo ==========================
 echo User $nuser
 echo ==========================
+  case "$nuser" in
+    *@*)
+        ihost=${nuser#*@}
+        nuser=${nuser%@*}
+        iuser=$( ruby -e "config = eval File.read('$CONFIG'); puts config[:INSTALL_USERS]['$ihost'] || config[:INSTALL_USERS]['']" )
+        [ -z "$iuser" ] && echo NO INSTALL_USERS FOR $ihost && exit 1
+        iuserhost=$iuser@$ihost
+        ;;
+    *)
+        iuser=$USER
+        ihost=$HOST
+        iuserhost="${USER}@${HOST}"
+        ;;
+  esac
+
+    os_version=$(ssh ${iuserhost} "sw_vers -productVersion")
+    buddy_version=$(ssh ${iuserhost} "sw_vers -buildVersion")
+    UIDS=$(ssh ${iuserhost} "dscl . -list /Users UniqueID")
+    [ -n "$UIDS" ] || { usage; echo "Unable to retrieve UIDs from $iuserhost ($UIDS)"; exit 1 ; }
 
     if echo start $UIDS end | grep " $nuser "; then
         echo USER $nuser already exists: updating only.
@@ -76,7 +87,7 @@ echo ==========================
         uid=$[ uid + 1 ]
         while echo start $UIDS end | grep " $uid " ; do uid=$[ uid + 1 ] ; done
         echo USER $nuser is new: creating.
-        cat <<END | ssh ${USERHOST} sudo -S -s
+        cat <<END | ssh ${iuserhost} sudo -S -s
 $PASSWORD
 rm -rf /Users/$nuser
 dscl . create /Users/$nuser
@@ -90,27 +101,33 @@ dscl . append /Groups/admin GroupMembership $nuser
 dscl . append /Groups/staff GroupMembership $nuser
 END
     fi
-    cat <<END | ssh ${USERHOST} sudo -S -s
+
+    # A bit excessive to rsync this for every user, but... eh.
+    rsync ${0%/*}/autostart_test_users.sshd.* ${iuserhost}:Autostart/
+    rsync ${0%/*}/autostart_test_users.stop ${iuserhost}:Autostart/
+
+    cat <<END | ssh ${iuserhost} sudo -S -s
 $PASSWORD
 echo Update started
 mkdir -p /Users/$nuser/.ssh
 touch /Users/$nuser/.ssh/authorized_keys
 chmod 644 /Users/$nuser/.ssh/authorized_keys
-cat /Users/$USER/.ssh/id_rsa.pub >> /Users/$nuser/.ssh/authorized_keys
-ln -s /Users/$USER/.rvm /Users/$nuser/
+cat /Users/$iuser/.ssh/id_rsa.pub >> /Users/$nuser/.ssh/authorized_keys
+cat /Users/$iuser/.ssh/authorized_keys >> /Users/$nuser/.ssh/authorized_keys
+ln -s /Users/$iuser/.rvm /Users/$nuser/
 mkdir -p /Users/$nuser/Library/Preferences
 defaults write /Users/$nuser/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
 defaults write /Users/$nuser/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
 defaults write /Users/$nuser/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion ${os_version}
 defaults write /Users/$nuser/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion ${buddy_version}
-cp /Users/$USER/Library/Preferences/com.apple.iphonesimulator.plist /Users/$nuser/Library/Preferences/com.apple.iphonesimulator.plist 
+cp /Users/$iuser/Library/Preferences/com.apple.iphonesimulator.plist /Users/$nuser/Library/Preferences/com.apple.iphonesimulator.plist 
 mkdir -p /Users/$nuser/Library/LaunchAgents
-sed -E 's/TEST_USER/$nuser/; s/MAIN_USER/$USER/' </Users/$USER/Autostart/autostart_test_users.sshd.plist >/Users/$nuser/Library/LaunchAgents/autostart_test_users.sshd.plist
+sed -E 's/TEST_USER/$nuser/; s/MAIN_USER/$iuser/' </Users/$iuser/Autostart/autostart_test_users.sshd.plist >/Users/$nuser/Library/LaunchAgents/autostart_test_users.sshd.plist
 rm -rf /Users/$nuser/ssh
 cp -r /etc/ssh /Users/$nuser/ssh
 sed -E -i~ 's/\/etc\//\/Users\/$nuser\//; s/#(ListenAddress|HostKey)/\1/' /Users/$nuser/ssh/sshd_config
 chown -R "${nuser}" "/Users/$nuser"
 END
-    echo y | ssh ${USERHOST} ssh $nuser@localhost echo SUCCESS FOR $nuser
+    echo y | ssh ${iuserhost} ssh $nuser@localhost echo SUCCESS FOR $nuser
 done
 
